Handle other exception messages
In newer JDKs the exception can differ, so instead of
"Received fatal alert: bad_certificate"
we can get the less useful message
"Received fatal alert: handshake_failure ==> expected: <true> but was: <false>"

This happens somewhat randomly, probably depends on timing & race conditions.